title:            Coding Matter
description:      Simple Matter of Coding
# put your disqus here
disqus_shortname: codingmatter
reading_time:     false
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://www.codingmatter.com

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'Blog'
    url: '/posts/'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  - title: 'Tags'
    url: '/tags/'
  - title: 'About'
    url: '/about/'

# Owner/author information
owner:          
  name:           Mike Chambers
  avatar:         images/avatar.jpg
  bio:            "Hi there, just another tech junkie here. I'm an Electrical/Computer Engineer by education, but mainly a C# developer by trade. I'm a big fan of embedded systems and enjoy programming Raspberry Pis and Arduinos in my free time. I look forward to documenting some of my projects here."
  email:          ...e@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  #twitter:        
  #facebook:       
  github:          miesch1
  stackexchange:  miesch1
  #linkedin:       
  #instagram:      
  #flickr:         
  #tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus: +MikeChambers1

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
# - title: "github"
#   url: "https://github.com/miesch1"
#  - title: "linkedin"
#    url: "https://www.linkedin.com/in/mike-chambers"
#   - title: "youtube"
#    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"
# Background image to be tiled on all pages
background: background.png

# Analytics and webmaster tools stuff goes here
google_analytics: UA-85975325-1
google_verify: 1fmuodimnXxew1Eqlfcvytfkr-fdm3ty_BW5laZlivQ
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Denver
locale:      en_US
future:      false  # publish future dated posts --  true, false (default) 
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   date

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
